### ISSUE TITLE
Consistent code style

### ISSUE THREAD

**Issue by binaryflesh** [lbryio/torba#64]
As a newer contributor, I have to explore the code to get an idea of what I can work on. I noticed a lot of inconsistency with code style. I am opening this issue because I'm going through and tidying up code while all the moving parts in lbry-sdk get re-worked.  There is no pylint config with this package so I am assuming it should resemble the sdk, I think #58 applies in that sense. I'm mainly making docstrings use " instead of ', and __set__ declarations uses (item,) instead of __set__ = item and other trivial PEPs. This is not a major issue but would be nice to have. I am opening this issue with the purpose to create a PR and have the effort be known to maintainers.

**Comment by eukreign** [comment]
There is indeed pylint configs for this project:
https://github.com/lbryio/torba/blob/9d3e1af69b7880b30ef0fdc772ce940acc082b88/setup.cfg#L12-L34

And pylint is run along with mypy on every build:
https://github.com/lbryio/torba/blob/9d3e1af69b7880b30ef0fdc772ce940acc082b88/.travis.yml#L17-L18
